import 'dart:async';
import 'package:flutter/material.dart';
import '../../../core/services/api_service.dart';

class TimedLine {
  final int startMs;
  final int? endMs;
  final String text;

  TimedLine({required this.startMs, this.endMs, required this.text});

  factory TimedLine.fromJson(Map<String, dynamic> json) => TimedLine(
        startMs: (json['startMs'] as num).toInt(),
        endMs: json['endMs'] != null ? (json['endMs'] as num).toInt() : null,
        text: json['text'] as String? ?? '',
      );
}

class SyncedLyricsPanel extends StatefulWidget {
  final String? songId;
  final Stream<Duration> positionStream;
  final Duration Function() currentPosition;

  /// When true, renders a "no lyrics" note instead of collapsing to nothing
  /// (used when the panel is the sole content, e.g. the bottom-bar sheet).
  final bool showEmptyMessage;

  const SyncedLyricsPanel({
    super.key,
    required this.songId,
    required this.positionStream,
    required this.currentPosition,
    this.showEmptyMessage = false,
  });

  @override
  State<SyncedLyricsPanel> createState() => _SyncedLyricsPanelState();
}

class _SyncedLyricsPanelState extends State<SyncedLyricsPanel> {
  List<TimedLine>? _lines;
  String? _plainText;
  // none | pending | ready | failed — pending means captions are still being
  // auto-aligned server-side; we show the plain text with a syncing note.
  String _syncStatus = 'none';
  // True when the captions were auto-transcribed from the audio.
  bool _autoGenerated = false;
  bool _loading = false;
  bool _collapsed = false;
  int _activeIndex = -1;
  String? _loadedSongId;
  StreamSubscription<Duration>? _posSub;
  Timer? _pendingRefetchTimer;

  final ScrollController _scrollCtrl = ScrollController();
  final List<GlobalKey> _lineKeys = [];

  @override
  void initState() {
    super.initState();
    _fetchLyrics();
    _posSub = widget.positionStream.listen(_onPosition);
  }

  @override
  void didUpdateWidget(covariant SyncedLyricsPanel old) {
    super.didUpdateWidget(old);
    if (widget.songId != old.songId) {
      _fetchLyrics();
    }
    if (widget.positionStream != old.positionStream) {
      _posSub?.cancel();
      _posSub = widget.positionStream.listen(_onPosition);
    }
  }

  @override
  void dispose() {
    _posSub?.cancel();
    _pendingRefetchTimer?.cancel();
    _scrollCtrl.dispose();
    super.dispose();
  }

  Future<void> _fetchLyrics() async {
    final id = widget.songId;
    if (id == null || id == _loadedSongId) return;
    _loadedSongId = id;
    setState(() {
      _loading = true;
      _lines = null;
      _plainText = null;
      _syncStatus = 'none';
      _autoGenerated = false;
      _activeIndex = -1;
    });

    try {
      final resp = await ApiService().get('songs/$id/lyrics');
      if (!mounted) return;
      final timed = resp['timedLines'];
      final plain = resp['plainText'] as String?;
      final status = (resp['status'] ?? 'none').toString();
      final parsed = <TimedLine>[];
      if (timed is List) {
        for (final item in timed) {
          if (item is Map<String, dynamic>) parsed.add(TimedLine.fromJson(item));
        }
      }
      setState(() {
        _lines = parsed.isEmpty ? null : parsed;
        _plainText = plain;
        _syncStatus = status;
        _autoGenerated = resp['autoGenerated'] == true;
        _lineKeys.clear();
        if (_lines != null) {
          for (var i = 0; i < _lines!.length; i++) {
            _lineKeys.add(GlobalKey());
          }
        }
      });
      // Captions are still being aligned server-side; check again shortly so
      // the synced lines appear mid-song without a manual refresh.
      _pendingRefetchTimer?.cancel();
      if (status == 'pending' && parsed.isEmpty) {
        _pendingRefetchTimer = Timer(const Duration(seconds: 15), () {
          if (!mounted) return;
          _loadedSongId = null;
          _fetchLyrics();
        });
      }
    } catch (_) {
      // no lyrics available
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  void _onPosition(Duration pos) {
    if (_lines == null || _lines!.isEmpty) return;
    final ms = pos.inMilliseconds;
    int best = -1;
    for (int i = 0; i < _lines!.length; i++) {
      if (_lines![i].startMs <= ms) {
        best = i;
      } else {
        break;
      }
    }
    if (best != _activeIndex) {
      setState(() => _activeIndex = best);
      _scrollToActive(best);
    }
  }

  void _scrollToActive(int index) {
    if (_collapsed || index < 0 || index >= _lineKeys.length) return;
    final key = _lineKeys[index];
    final ctx = key.currentContext;
    if (ctx != null) {
      Scrollable.ensureVisible(
        ctx,
        alignment: 0.4,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeInOut,
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final hasLyrics =
        (_lines != null && _lines!.isNotEmpty) ||
        (_plainText != null && _plainText!.trim().isNotEmpty);
    if (!hasLyrics && !_loading) {
      if (!widget.showEmptyMessage) return const SizedBox.shrink();
      final scheme = Theme.of(context).colorScheme;
      return Padding(
        padding: const EdgeInsets.all(24),
        child: Center(
          child: Text(
            'No lyrics for this song yet.',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: scheme.onSurfaceVariant,
                ),
          ),
        ),
      );
    }

    final scheme = Theme.of(context).colorScheme;
    final textTheme = Theme.of(context).textTheme;

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: scheme.surfaceContainerHighest.withValues(alpha: 0.35),
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
          color: scheme.onSurface.withValues(alpha: 0.12),
        ),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          InkWell(
            borderRadius: const BorderRadius.vertical(top: Radius.circular(14)),
            onTap: () => setState(() => _collapsed = !_collapsed),
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
              child: Row(
                children: [
                  Text(
                    '♪ Lyrics',
                    style: textTheme.labelMedium?.copyWith(
                      color: scheme.onSurfaceVariant,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  if (_autoGenerated) ...[
                    const SizedBox(width: 8),
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 2,
                      ),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10),
                        border: Border.all(
                          color: scheme.onSurface.withValues(alpha: 0.2),
                        ),
                      ),
                      child: Text(
                        'Auto-generated',
                        style: textTheme.labelSmall?.copyWith(
                          fontSize: 9,
                          color: scheme.onSurfaceVariant
                              .withValues(alpha: 0.8),
                        ),
                      ),
                    ),
                  ],
                  const Spacer(),
                  Icon(
                    _collapsed ? Icons.expand_more : Icons.expand_less,
                    size: 18,
                    color: scheme.onSurfaceVariant,
                  ),
                ],
              ),
            ),
          ),
          if (!_collapsed)
            ConstrainedBox(
              constraints: const BoxConstraints(maxHeight: 200),
              child: _loading
                  ? const Padding(
                      padding: EdgeInsets.all(20),
                      child: Center(
                        child: SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        ),
                      ),
                    )
                  : _lines != null && _lines!.isNotEmpty
                      ? ListView.builder(
                          controller: _scrollCtrl,
                          padding: const EdgeInsets.fromLTRB(14, 0, 14, 14),
                          itemCount: _lines!.length,
                          itemBuilder: (context, i) {
                            final isActive = i == _activeIndex;
                            final isPast = i < _activeIndex;
                            return Padding(
                              key: _lineKeys[i],
                              padding: const EdgeInsets.symmetric(vertical: 3),
                              child: AnimatedDefaultTextStyle(
                                duration: const Duration(milliseconds: 280),
                                style: textTheme.bodyMedium!.copyWith(
                                  color: isActive
                                      ? scheme.onSurface
                                      : isPast
                                          ? scheme.onSurface.withValues(alpha: 0.35)
                                          : scheme.onSurface.withValues(alpha: 0.6),
                                  fontWeight:
                                      isActive ? FontWeight.w700 : FontWeight.w400,
                                  fontSize: isActive ? 15 : 14,
                                ),
                                child: Text(
                                  _lines![i].text.isEmpty ? '♪' : _lines![i].text,
                                ),
                              ),
                            );
                          },
                        )
                      : _plainText != null
                          ? SingleChildScrollView(
                              padding:
                                  const EdgeInsets.fromLTRB(14, 0, 14, 14),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  if (_syncStatus == 'pending')
                                    Padding(
                                      padding:
                                          const EdgeInsets.only(bottom: 8),
                                      child: Text(
                                        'Syncing lyrics…',
                                        style: textTheme.labelSmall?.copyWith(
                                          color: scheme.onSurfaceVariant
                                              .withValues(alpha: 0.7),
                                          fontStyle: FontStyle.italic,
                                        ),
                                      ),
                                    ),
                                  Text(
                                    _plainText!,
                                    style: textTheme.bodyMedium?.copyWith(
                                      color: scheme.onSurfaceVariant,
                                      height: 1.6,
                                    ),
                                  ),
                                ],
                              ),
                            )
                          : const SizedBox.shrink(),
            ),
        ],
      ),
    );
  }
}
