import { BadRequestException, Injectable, Logger } from '@nestjs/common';
import { getSupabaseClient } from '../config/supabase.config';
import { signSongAudioUrl } from '../common/song-audio.util';
import {
  AlignedWord,
  LyricsAlignmentProvider,
  LyricsTranscriptionProvider,
} from './lyrics-alignment.provider';
import { ElevenLabsAlignmentProvider } from './elevenlabs-alignment.provider';

export interface TimedLine {
  startMs: number;
  endMs: number;
  text: string;
}

export interface LyricsRecord {
  plainText: string | null;
  timedLines: TimedLine[] | null;
  provider: string | null;
  status: 'none' | 'pending' | 'ready' | 'failed';
  /** True when the lyrics were transcribed from audio, not typed by the artist. */
  autoGenerated: boolean;
  updatedAt: string | null;
}

/**
 * Owns the song_lyrics table: saving artist lyrics and force-aligning them to
 * the audio in the background (automatic closed captions). Alignment runs like
 * sample generation — fire-and-forget after upload, never blocking the caller.
 */
@Injectable()
export class LyricsService {
  private readonly logger = new Logger(LyricsService.name);
  private readonly provider: LyricsAlignmentProvider &
    LyricsTranscriptionProvider;

  constructor(elevenLabs: ElevenLabsAlignmentProvider) {
    // Swap the injected provider here to change alignment vendors.
    this.provider = elevenLabs;
  }

  async getLyrics(songId: string): Promise<LyricsRecord> {
    const supabase = getSupabaseClient();
    const { data, error } = await supabase
      .from('song_lyrics')
      .select(
        'plain_text, timed_lines, provider, status, auto_generated, updated_at',
      )
      .eq('song_id', songId)
      .maybeSingle();

    if (error) {
      if (
        (error as { code?: string }).code === '42P01' ||
        (error.message ?? '').toLowerCase().includes('song_lyrics')
      ) {
        return this.emptyRecord();
      }
      throw new BadRequestException(`Failed to fetch lyrics: ${error.message}`);
    }
    if (!data) return this.emptyRecord();
    return this.toRecord(data);
  }

  /**
   * Save lyrics for a song. Explicit `timedLines` are treated as a manual
   * sync and stored as-is; otherwise a non-empty `plainText` queues automatic
   * alignment in the background (when the provider is configured).
   */
  async upsertLyrics(
    songId: string,
    input: { plainText?: string; timedLines?: TimedLine[] | null },
  ): Promise<LyricsRecord> {
    const supabase = getSupabaseClient();
    const now = new Date().toISOString();
    const row: Record<string, unknown> = { song_id: songId, updated_at: now };

    const hasManualTimedLines =
      Array.isArray(input.timedLines) && input.timedLines.length > 0;
    const plainText =
      input.plainText !== undefined ? input.plainText.trim() : undefined;

    if (input.plainText !== undefined) {
      row.plain_text = plainText || null;
    }

    if (input.timedLines !== undefined) {
      row.timed_lines = hasManualTimedLines ? input.timedLines : null;
    }

    let queueAlignment = false;
    if (hasManualTimedLines) {
      // Artist supplied their own timings; don't overwrite them.
      row.provider = 'manual';
      row.status = 'ready';
      row.aligned_at = now;
      row.error = null;
      row.auto_generated = false;
    } else if (input.plainText !== undefined) {
      // Artist-authored text replaces any auto-generated transcript.
      row.auto_generated = false;
      if (plainText) {
        if (this.provider.isConfigured()) {
          row.status = 'pending';
          queueAlignment = true;
        } else {
          // No aligner available: plain lyrics still display, just unsynced.
          row.status = 'none';
        }
        // Text changed — any previously aligned lines no longer match it.
        row.timed_lines = null;
        row.error = null;
      } else {
        // Lyrics cleared.
        row.status = 'none';
        row.timed_lines = null;
        row.error = null;
      }
    }

    const { data, error } = await supabase
      .from('song_lyrics')
      .upsert(row, { onConflict: 'song_id' })
      .select(
        'plain_text, timed_lines, provider, status, auto_generated, updated_at',
      )
      .single();

    if (error) {
      throw new BadRequestException(`Failed to save lyrics: ${error.message}`);
    }

    if (queueAlignment) {
      this.alignLyricsInBackground(songId);
    }

    return this.toRecord(data);
  }

  /**
   * Fire-and-forget forced alignment, mirroring generateSampleInBackground.
   * Failures mark the row `failed` but keep the plain lyrics usable.
   */
  alignLyricsInBackground(songId: string): void {
    void this.alignLyrics(songId).catch((err) => {
      this.logger.warn(
        `Lyrics alignment failed for song ${songId}: ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
    });
  }

  /**
   * Auto-caption fallback: transcribe a song that has no lyrics on file
   * (speech-to-text) and store the result flagged as auto-generated. Never
   * overwrites artist-provided lyrics unless `force` is set.
   */
  transcribeLyricsInBackground(songId: string, options?: { force?: boolean }): void {
    void this.transcribeLyrics(songId, options?.force ?? false).catch((err) => {
      this.logger.warn(
        `Lyrics transcription failed for song ${songId}: ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
    });
  }

  /**
   * Queue transcription for approved songs that have no lyrics yet.
   * Runs sequentially in the background (one provider call at a time) so a
   * large backfill doesn't hammer the API. Returns the number of songs queued.
   */
  async backfillMissingLyrics(limit = 25): Promise<{ queued: number; songIds: string[] }> {
    if (!this.provider.isConfigured()) {
      throw new BadRequestException(
        'ELEVENLABS_API_KEY is not configured; cannot transcribe.',
      );
    }
    const supabase = getSupabaseClient();
    const { data: songs, error } = await supabase
      .from('songs')
      .select('id, song_lyrics(plain_text, status)')
      .eq('status', 'approved')
      .order('created_at', { ascending: false })
      .limit(Math.min(Math.max(limit, 1), 100));
    if (error) {
      throw new BadRequestException(`Failed to list songs: ${error.message}`);
    }

    const targets = (songs ?? [])
      .filter((song) => {
        const lyrics = Array.isArray(song.song_lyrics)
          ? song.song_lyrics[0]
          : song.song_lyrics;
        if (!lyrics) return true;
        const hasText = ((lyrics.plain_text as string | null) ?? '').trim().length > 0;
        return !hasText && lyrics.status !== 'pending';
      })
      .map((song) => song.id as string);

    // Fire-and-forget chain; each song completes before the next starts.
    void (async () => {
      for (const id of targets) {
        try {
          await this.transcribeLyrics(id, false);
        } catch (err) {
          this.logger.warn(
            `Backfill transcription failed for song ${id}: ${
              err instanceof Error ? err.message : String(err)
            }`,
          );
        }
      }
      this.logger.log(`Lyrics backfill finished (${targets.length} songs).`);
    })();

    return { queued: targets.length, songIds: targets };
  }

  private async transcribeLyrics(songId: string, force: boolean): Promise<void> {
    const supabase = getSupabaseClient();
    const { data: existing } = await supabase
      .from('song_lyrics')
      .select('plain_text, status, auto_generated')
      .eq('song_id', songId)
      .maybeSingle();

    const hasArtistText =
      ((existing?.plain_text as string | null) ?? '').trim().length > 0 &&
      existing?.auto_generated !== true;
    if (hasArtistText && !force) return;
    if (existing?.status === 'pending') return;
    if (!this.provider.isConfigured()) return;

    const now = new Date().toISOString();
    await supabase.from('song_lyrics').upsert(
      {
        song_id: songId,
        status: 'pending',
        auto_generated: true,
        error: null,
        updated_at: now,
      },
      { onConflict: 'song_id' },
    );

    try {
      const audio = await this.downloadSongAudio(songId);
      const result = await this.provider.transcribe(audio);
      const timedLines = groupTranscriptWordsIntoLines(result.words);
      if (!timedLines.length) {
        throw new Error('Transcription produced no caption lines');
      }
      const plainText = timedLines.map((line) => line.text).join('\n');

      await supabase
        .from('song_lyrics')
        .update({
          plain_text: plainText,
          timed_lines: timedLines,
          provider: result.provider,
          status: 'ready',
          auto_generated: true,
          aligned_at: new Date().toISOString(),
          error: null,
          updated_at: new Date().toISOString(),
        })
        .eq('song_id', songId);
      this.logger.log(
        `Auto-transcribed lyrics for song ${songId}: ${timedLines.length} lines via ${result.provider}`,
      );
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      await supabase
        .from('song_lyrics')
        .update({
          status: 'failed',
          error: message.slice(0, 500),
          updated_at: new Date().toISOString(),
        })
        .eq('song_id', songId);
      throw err;
    }
  }

  private async downloadSongAudio(songId: string): Promise<Buffer> {
    const supabase = getSupabaseClient();
    const { data: song } = await supabase
      .from('songs')
      .select('audio_url')
      .eq('id', songId)
      .single();
    if (!song?.audio_url) {
      throw new Error('Song has no audio to caption');
    }
    const signedUrl = (await signSongAudioUrl(song.audio_url)) ?? song.audio_url;
    const audioRes = await fetch(signedUrl);
    if (!audioRes.ok) {
      throw new Error(
        `Failed to download song audio: ${audioRes.status} ${audioRes.statusText}`,
      );
    }
    const audio = Buffer.from(await audioRes.arrayBuffer());
    if (!audio.length) throw new Error('Downloaded song audio is empty');
    return audio;
  }

  private async alignLyrics(songId: string): Promise<void> {
    const supabase = getSupabaseClient();
    try {
      const { data: lyricsRow } = await supabase
        .from('song_lyrics')
        .select('plain_text')
        .eq('song_id', songId)
        .maybeSingle();
      const plainText = (lyricsRow?.plain_text ?? '').trim();
      if (!plainText) return;

      const audio = await this.downloadSongAudio(songId);
      const result = await this.provider.align(audio, plainText);
      const timedLines = groupWordsIntoLines(plainText, result.words);
      if (!timedLines.length) {
        throw new Error('Alignment produced no caption lines');
      }

      await supabase
        .from('song_lyrics')
        .update({
          timed_lines: timedLines,
          provider: result.provider,
          status: 'ready',
          aligned_at: new Date().toISOString(),
          error: null,
          updated_at: new Date().toISOString(),
        })
        .eq('song_id', songId);
      this.logger.log(
        `Aligned lyrics for song ${songId}: ${timedLines.length} lines via ${result.provider}`,
      );
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      await supabase
        .from('song_lyrics')
        .update({
          status: 'failed',
          error: message.slice(0, 500),
          updated_at: new Date().toISOString(),
        })
        .eq('song_id', songId);
      throw err;
    }
  }

  private toRecord(data: {
    plain_text?: string | null;
    timed_lines?: unknown;
    provider?: string | null;
    status?: string | null;
    auto_generated?: boolean | null;
    updated_at?: string | null;
  }): LyricsRecord {
    return {
      plainText: data.plain_text ?? null,
      timedLines: (data.timed_lines as TimedLine[] | null) ?? null,
      provider: data.provider ?? null,
      status: (data.status as LyricsRecord['status']) ?? 'none',
      autoGenerated: data.auto_generated === true,
      updatedAt: data.updated_at ?? null,
    };
  }

  private emptyRecord(): LyricsRecord {
    return {
      plainText: null,
      timedLines: null,
      provider: null,
      status: 'none',
      autoGenerated: false,
      updatedAt: null,
    };
  }
}

/**
 * Group provider word timings back into the artist's lyric lines.
 *
 * The aligner was given the exact lyrics text, so its word stream follows the
 * text in order. We walk that stream, consuming one aligned word per
 * whitespace-separated token of each line; a line's window spans its first
 * word's start to its last word's end.
 */
export function groupWordsIntoLines(
  plainText: string,
  words: AlignedWord[],
): TimedLine[] {
  const lines = plainText
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  const timed: TimedLine[] = [];
  let cursor = 0;

  for (const line of lines) {
    const tokenCount = line.split(/\s+/).filter(Boolean).length;
    if (tokenCount === 0) continue;
    if (cursor >= words.length) break;

    const take = Math.min(tokenCount, words.length - cursor);
    const first = words[cursor];
    const last = words[cursor + take - 1];
    cursor += take;

    timed.push({
      startMs: Math.max(0, Math.round(first.startSeconds * 1000)),
      endMs: Math.max(0, Math.round(last.endSeconds * 1000)),
      text: line,
    });
  }

  return timed;
}

/**
 * Group a raw speech-to-text word stream into caption lines.
 *
 * Transcripts have no artist line breaks to anchor to, so we break lines
 * heuristically: a silence gap between words longer than GAP_BREAK_MS starts a
 * new line (phrase boundary in the vocal), and lines are capped at
 * MAX_WORDS_PER_LINE so captions stay readable.
 */
export function groupTranscriptWordsIntoLines(words: AlignedWord[]): TimedLine[] {
  const GAP_BREAK_MS = 1200;
  const MAX_WORDS_PER_LINE = 8;

  const timed: TimedLine[] = [];
  let current: AlignedWord[] = [];

  const flush = () => {
    if (!current.length) return;
    timed.push({
      startMs: Math.max(0, Math.round(current[0].startSeconds * 1000)),
      endMs: Math.max(
        0,
        Math.round(current[current.length - 1].endSeconds * 1000),
      ),
      text: current.map((w) => w.word).join(' '),
    });
    current = [];
  };

  for (const word of words) {
    if (current.length) {
      const prev = current[current.length - 1];
      const gapMs = (word.startSeconds - prev.endSeconds) * 1000;
      if (gapMs > GAP_BREAK_MS || current.length >= MAX_WORDS_PER_LINE) {
        flush();
      }
    }
    current.push(word);
  }
  flush();

  return timed;
}
