'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { Pause, Play } from 'lucide-react';
import { songsApi } from '@/lib/api';
import { usePlayback } from '@/components/playback';
import { ArtworkImage } from '@/components/common/ArtworkImage';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { cn } from '@/lib/utils';

export interface LyricsPlayerSong {
  id: string;
  title: string;
  artistName: string;
  artworkUrl?: string | null;
}

interface TimedLine {
  startMs: number;
  endMs?: number;
  text: string;
}

type LyricsStatus = 'none' | 'pending' | 'ready' | 'failed';

function formatTime(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return '0:00';
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Full-track player with karaoke-style synced lyrics.
 *
 * Plays through the global playback session (source 'discography'), so radio
 * and other page audio stop automatically. Play/pause/seek only work for
 * tracks the current user is entitled to stream in full (own uploads,
 * purchases, or admin). With `editable`, the lyrics text can be corrected in
 * place; saving re-syncs captions server-side.
 */
export function LyricsPlayer({
  song,
  editable = false,
  className,
}: {
  song: LyricsPlayerSong;
  editable?: boolean;
  className?: string;
}) {
  const { state, actions } = usePlayback();
  const [loadingStream, setLoadingStream] = useState(false);
  const [playError, setPlayError] = useState<string | null>(null);

  // Lyrics state
  const [lines, setLines] = useState<TimedLine[] | null>(null);
  const [plainText, setPlainText] = useState<string | null>(null);
  const [status, setStatus] = useState<LyricsStatus>('none');
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [lyricsLoading, setLyricsLoading] = useState(true);

  // Editor state
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState('');
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const containerRef = useRef<HTMLDivElement>(null);
  const activeLineRef = useRef<HTMLParagraphElement>(null);

  const isActive =
    state.source === 'discography' && state.track?.id === song.id;
  const isPlaying = isActive && state.isPlaying;
  const currentTimeMs = isActive ? Math.round(state.currentTime * 1000) : -1;

  const fetchLyrics = useCallback(async () => {
    setLyricsLoading(true);
    try {
      const res = await songsApi.getLyrics(song.id);
      setLines((res.data?.timedLines as TimedLine[] | null) ?? null);
      setPlainText(res.data?.plainText ?? null);
      setStatus(res.data?.status ?? 'none');
      setAutoGenerated(res.data?.autoGenerated === true);
    } catch {
      setLines(null);
      setPlainText(null);
      setStatus('none');
    } finally {
      setLyricsLoading(false);
    }
  }, [song.id]);

  useEffect(() => {
    setEditing(false);
    setSaveError(null);
    setPlayError(null);
    void fetchLyrics();
  }, [fetchLyrics]);

  // Re-check while server-side sync is running so lines appear when ready.
  useEffect(() => {
    if (status !== 'pending') return;
    const timer = setTimeout(() => void fetchLyrics(), 15_000);
    return () => clearTimeout(timer);
  }, [status, fetchLyrics]);

  const handlePlayPause = async () => {
    setPlayError(null);
    if (isActive) {
      await actions.togglePlay();
      return;
    }
    if (loadingStream) return;
    setLoadingStream(true);
    try {
      const res = await songsApi.getStreamUrl(song.id);
      const url = res.data?.url;
      if (!url) {
        setPlayError('Could not load the full track for this song.');
        return;
      }
      actions.loadTrack(
        {
          id: song.id,
          title: song.title,
          artistName: song.artistName,
          artistId: '',
          artworkUrl: song.artworkUrl ?? null,
          audioUrl: url,
          durationSeconds: 0,
        },
        'discography',
        true,
      );
    } catch {
      setPlayError(
        'Could not play this song. Full playback is only available for songs you own.',
      );
    } finally {
      setLoadingStream(false);
    }
  };

  const handleSeek = (value: number) => {
    if (!isActive) return;
    actions.seek(value);
  };

  // Karaoke highlight: last line whose start has passed.
  let activeIndex = -1;
  if (lines && currentTimeMs >= 0) {
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].startMs <= currentTimeMs) activeIndex = i;
      else break;
    }
  }

  useEffect(() => {
    if (activeLineRef.current && containerRef.current) {
      activeLineRef.current.scrollIntoView({
        behavior: 'smooth',
        block: 'center',
      });
    }
  }, [activeIndex]);

  const startEditing = () => {
    setDraft(plainText ?? '');
    setSaveError(null);
    setEditing(true);
  };

  const handleSave = async () => {
    if (saving) return;
    setSaving(true);
    setSaveError(null);
    try {
      const res = await songsApi.upsertLyrics(song.id, {
        plainText: draft.trim(),
      });
      setPlainText(res.data?.plainText ?? null);
      setLines((res.data?.timedLines as TimedLine[] | null) ?? null);
      setStatus(res.data?.status ?? 'none');
      setAutoGenerated(res.data?.autoGenerated === true);
      setEditing(false);
    } catch (err) {
      setSaveError(
        err instanceof Error ? err.message : 'Failed to save lyrics.',
      );
    } finally {
      setSaving(false);
    }
  };

  const duration = isActive ? state.duration : 0;
  const hasTimedLines = !!lines && lines.length > 0;

  return (
    <div className={cn('flex flex-col gap-4', className)}>
      {/* Track header + transport */}
      <div className="flex items-center gap-4">
        <ArtworkImage
          src={song.artworkUrl ?? null}
          alt={song.title}
          className="h-16 w-16 rounded-lg object-cover flex-shrink-0"
        />
        <div className="min-w-0 flex-1">
          <p className="font-semibold text-foreground truncate">{song.title}</p>
          <p className="text-sm text-muted-foreground truncate">
            {song.artistName}
          </p>
          <div className="mt-1 flex flex-wrap gap-1.5">
            {status === 'pending' && (
              <span className="text-[11px] rounded-full bg-amber-500/15 text-amber-600 px-2 py-0.5">
                Syncing…
              </span>
            )}
            {status === 'ready' && (
              <span className="text-[11px] rounded-full bg-emerald-500/15 text-emerald-600 px-2 py-0.5">
                Synced
              </span>
            )}
            {status === 'failed' && (
              <span className="text-[11px] rounded-full bg-destructive/15 text-destructive px-2 py-0.5">
                Sync failed
              </span>
            )}
            {autoGenerated && (
              <span className="text-[11px] rounded-full bg-sky-500/15 text-sky-600 px-2 py-0.5">
                Auto-generated
              </span>
            )}
          </div>
        </div>
        <Button
          type="button"
          size="icon"
          className="h-12 w-12 rounded-full flex-shrink-0"
          onClick={() => void handlePlayPause()}
          disabled={loadingStream}
          aria-label={isPlaying ? 'Pause' : 'Play'}
        >
          {isPlaying ? (
            <Pause className="h-5 w-5" />
          ) : (
            <Play className="h-5 w-5 ml-0.5" />
          )}
        </Button>
      </div>

      {/* Seek bar */}
      <div className="flex items-center gap-3">
        <span className="text-[11px] tabular-nums text-muted-foreground w-10 text-right">
          {formatTime(isActive ? state.currentTime : 0)}
        </span>
        <input
          type="range"
          min={0}
          max={Math.max(duration, 1)}
          step={1}
          value={isActive ? Math.min(state.currentTime, duration || 0) : 0}
          onChange={(e) => handleSeek(Number(e.target.value))}
          disabled={!isActive || !duration}
          className="flex-1 accent-primary h-1.5 cursor-pointer disabled:cursor-not-allowed"
          aria-label="Seek"
        />
        <span className="text-[11px] tabular-nums text-muted-foreground w-10">
          {formatTime(duration)}
        </span>
      </div>

      {playError && <p className="text-sm text-destructive">{playError}</p>}

      {/* Lyrics: karaoke view or editor */}
      {editing ? (
        <div className="space-y-2">
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            rows={12}
            placeholder="Lyrics, one line per lyric line."
            className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm resize-y"
          />
          {saveError && <p className="text-sm text-destructive">{saveError}</p>}
          <div className="flex justify-end gap-2">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => setEditing(false)}
              disabled={saving}
            >
              Cancel
            </Button>
            <Button
              type="button"
              size="sm"
              onClick={() => void handleSave()}
              disabled={saving}
            >
              {saving ? 'Saving…' : 'Save lyrics'}
            </Button>
          </div>
          <p className="text-xs text-muted-foreground">
            Saving re-syncs the captions to the audio automatically (takes
            about a minute).
          </p>
        </div>
      ) : (
        <div
          ref={containerRef}
          className="max-h-[320px] min-h-[160px] overflow-y-auto scroll-smooth rounded-lg border border-border bg-card/50 px-4 py-3"
        >
          {lyricsLoading && (
            <p className="text-sm text-muted-foreground animate-pulse">
              Loading lyrics…
            </p>
          )}

          {!lyricsLoading && hasTimedLines && (
            <div className="space-y-1.5">
              {lines!.map((line, i) => {
                const isActiveLine = i === activeIndex;
                return (
                  <p
                    key={i}
                    ref={isActiveLine ? activeLineRef : undefined}
                    className={cn(
                      'text-base leading-relaxed transition-all duration-300',
                      isActiveLine
                        ? 'text-foreground font-semibold scale-[1.02] origin-left'
                        : i < activeIndex
                          ? 'text-muted-foreground/50'
                          : 'text-muted-foreground',
                    )}
                  >
                    {line.text || '♪'}
                  </p>
                );
              })}
            </div>
          )}

          {!lyricsLoading && !hasTimedLines && plainText && (
            <div>
              {status === 'pending' && (
                <p className="text-xs text-muted-foreground/70 animate-pulse mb-2">
                  Syncing lyrics to the audio…
                </p>
              )}
              <p className="text-sm text-muted-foreground whitespace-pre-wrap leading-relaxed">
                {plainText}
              </p>
            </div>
          )}

          {!lyricsLoading && !hasTimedLines && !plainText && (
            <p className="text-sm text-muted-foreground">
              No lyrics for this song yet.
              {status === 'pending' && ' Captions are being generated…'}
            </p>
          )}
        </div>
      )}

      {editable && !editing && (
        <div className="flex justify-end">
          <Button type="button" variant="outline" size="sm" onClick={startEditing}>
            Edit lyrics
          </Button>
        </div>
      )}
    </div>
  );
}

/** LyricsPlayer inside a modal — used from song lists (library, my songs). */
export function LyricsPlayerDialog({
  song,
  editable = false,
  onClose,
}: {
  song: LyricsPlayerSong | null;
  editable?: boolean;
  onClose: () => void;
}) {
  return (
    <Dialog open={song !== null} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Lyrics</DialogTitle>
        </DialogHeader>
        {song && <LyricsPlayer song={song} editable={editable} />}
      </DialogContent>
    </Dialog>
  );
}
