// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHnCoZ34QZmlb7rxae02a-kLmSGutmwDI',
    appId: '1:479427085382:android:8dedbb3fb02c0e7b05b647',
    messagingSenderId: '479427085382',
    projectId: 'radioapp-4c14a',
    storageBucket: 'radioapp-4c14a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEzAK0K2iqP21LedVuAhqS6vNbdBzRAo',
    appId: '1:479427085382:ios:1d5578183b068eae05b647',
    messagingSenderId: '479427085382',
    projectId: 'radioapp-4c14a',
    storageBucket: 'radioapp-4c14a.firebasestorage.app',
    iosBundleId: 'com.radioapp.radioApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy9nUAKJ18Tgb63CHX61Vte7bk0W82DTU',
    appId: '1:479427085382:web:48e0d6ba9d20324305b647',
    messagingSenderId: '479427085382',
    projectId: 'radioapp-4c14a',
    authDomain: 'radioapp-4c14a.firebaseapp.com',
    storageBucket: 'radioapp-4c14a.firebasestorage.app',
    measurementId: 'G-6X5T3SHJVZ',
  );
}
