// File generated by flutterfire_cli
// This file allows Firebase to be initialized without explicit options
// If you haven't set up Firebase yet, you can temporarily use this

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return null; // Web not supported yet
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Check if Android config is set up (not using placeholder values)
        if (android.apiKey == 'YOUR_API_KEY') {
          return null; // Not configured yet
        }
        return android;
      case TargetPlatform.iOS:
        // Check if iOS config is set up (not using placeholder values)
        if (ios.apiKey == 'YOUR_API_KEY') {
          return null; // Not configured yet
        }
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return null; // Not supported yet
      default:
        return null;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    // Add other Android-specific options from your google-services.json
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    // Add other iOS-specific options from your GoogleService-Info.plist
  );
}
